Dodanie ogólnych plików i zdj
QuickerMaths/projekt-grupa-1 pull request #6
Opened 2023-01-26 17:50 UTC by Sanjos55555

1.Dodałem mixina do vars
2.Dodałem zmienne do vars
3. Dodałem plik customer-reviews.html
4. Dodałem plik _customer-reviews.scss
5. Dodałem zdj do mojej sekcji.

2023-01-26 21:51 UTC, QuickerMaths requested changes

2023-01-26 21:51 UTC, QuickerMaths commented on src/sass/utils/_vars.scss
> +@mixin ff-fw-fs-lh-ls($ff-raleway, $fw, $fs, $lh, $ls) {
jakbyś mógł zmienić nazwę mixina na np font-properties, bo tak jest niezbyt czytelnie

2023-01-26 22:04 UTC, Sanjos55555 commented on src/sass/utils/_vars.scss
> +@mixin ff-fw-fs-lh-ls($ff-raleway, $fw, $fs, $lh, $ls) {
ok

2023-01-27 00:39 UTC, QuickerMaths approved these changes

2023-01-27 00:39 UTC, QuickerMaths commented on src/customer-reviews.html
> +      <div class="container-reviews__points-block">
zamiast divów w tel liście powinieneś użyć tagów ul i  li

2023-01-28 15:37 UTC, merged